<!--
  Stride.Sdk.Runtime.Windows - Targets file
  
  Simply imports the Stride.Sdk.Runtime targets.
-->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <!-- Import the base Stride.Sdk.Runtime targets -->
  <Import Project="Sdk.targets" Sdk="Stride.Sdk.Runtime" />

</Project>
