<Project Sdk="Stride.Sdk.Runtime">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <StrideAssemblyProcessor>true</StrideAssemblyProcessor>
    <StrideAssemblyProcessorOptions>--serialization --parameter-key</StrideAssemblyProcessorOptions>
    <StrideBuildTags>*</StrideBuildTags>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\shared\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\core\Stride.Core.Mathematics\Stride.Core.Mathematics.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Stride.Native.Libs.targets">
      <SubType>Designer</SubType>
    </None>
    <None Include="StrideNative.h" />
    <None Include="StrideNative.cpp" />
  </ItemGroup>
</Project>