<Project>
  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildProjectDirectory), 'Directory.Build.props'))/sdk/Stride.Build.Sdk.Editor/Sdk/Sdk.props" />  

  <PropertyGroup>
    <TargetFramework>$(StrideXplatEditorTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  
  <ItemGroup>
    <Compile Include="../../shared/SharedAssemblyInfo.cs">
      <Link>Properties/SharedAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Stride.Editor.Avalonia/Stride.Editor.Avalonia.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- TODO xplat-editor that reference shouldn't be explicit and such assembly should be loaded as external plugins -->
    <ProjectReference Include="../Stride.Assets.Editor.Avalonia/Stride.Assets.Editor.Avalonia.csproj" />
  </ItemGroup>

  <Import Project="$(StrideRoot)sources/sdk/Stride.Build.Sdk.Editor/Sdk/Sdk.targets" />
</Project>
