<Project Sdk="Stride.Sdk.Runtime">
  <PropertyGroup>
    <StrideAssemblyProcessor>true</StrideAssemblyProcessor>
    <StrideAssemblyProcessorOptions>$(StrideAssemblyProcessorDefaultOptions)</StrideAssemblyProcessorOptions>
    <StrideBuildTags>*</StrideBuildTags>
    <StridePackAssets>true</StridePackAssets>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\shared\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Stride.Engine\Stride.Engine.csproj" />
  </ItemGroup>
</Project>