<Project Sdk="Stride.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <StrideAssemblyProcessor>true</StrideAssemblyProcessor>
    <StrideAssemblyProcessorOptions>$(StrideAssemblyProcessorDefaultOptions)</StrideAssemblyProcessorOptions>
    <TargetFramework>$(StrideEditorTargetFramework)</TargetFramework>
    <StrideBuildTags>WindowsTools</StrideBuildTags>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mono.Options" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\shared\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Stride.Assets\Stride.Assets.csproj" />
  </ItemGroup>
</Project>